### ISSUE TITLE
Error when syncing to a MySQL database

### ISSUE THREAD

**Issue by LouisNowell-Nicolle** [vunder/dotmimsync#10]
I get this error when trying to sync 
```
2022-12-22 13:43:53.997 24899-24922/ com.XXXXX E/AndroidRuntime: FATAL EXCEPTION: SyncAdapterThread-1
    Process: com.XXXXX:sync, PID: 24899
    java.net.ProtocolException: Unexpected status line: J������
        at okhttp3.internal.http.StatusLine$Companion.parse(StatusLine.kt:80)
        at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:180)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:110)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at com.mimetis.dotmim.sync.web.client.DotmimServiceImpl$special$$inlined$-addInterceptor$1.intercept(OkHttpClient.kt:1101)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

Here's the kotlin code I am using for the sync
```kt
suspend fun dotmim(
        account: Account?,
        extras: Bundle?,
        authority: String?,
        provider: ContentProviderClient?,
        syncResult: SyncResult?) {
        Log.d(TAG,"DOTMIN START")
        val serverConnection = "http://10.0.2.2:3306/"
        Log.d(TAG,serverConnection)
        val clientProvider = SqliteSyncProvider(SQLiteDatabaseHelper(context))


        val sc = SetupColumns()
        sc.addAll(listOf("firstName","lastName"))
        val sts = SetupTables()
        sts.add(SetupTable("User", columns = sc))
        val ss = SyncSetup(tables = sts)
        val so = SyncOptions()
        val rm = WebClientOrchestrator(serverConnection,"")
        val agent = SyncAgent(clientProvider, rm, so, ss, "temp")
        val s1: Any = agent.synchronize()
        Log.d(TAG,s1.toString())
        Log.d(TAG,"DOTMIN END")
    }
```

I can access the MySQL server though other methods, interestingly when I open the url in a browser I find
```
J���
8.0.31�½���lk!%`:K�ےےے�ےك����������,c7k'g^*0�caching_sha2_password�!��ے„#08S01Got packets out of order
```
which seems to be what the library is trying to process? If there are any code examples that would be useful thanks

**Comment by LouisNowell-Nicolle** [comment]
Eventually I realized I was sending the sync request to the SQL server URL instead of the Dotmim server URL
